export const generateWidgetCode = (config: any) => {
  const { type, handle, welcomeMessage, position, primaryColor, size } = config;

  let widgetCode = '';

  switch (type) {
    case 'whatsapp':
      widgetCode = `
        <!-- WhatsApp Widget generated by Widgetify -->
        <script>
          (function () {
            var options = {
              whatsapp: "${handle}",
              call_to_action: "${welcomeMessage}",
              position: "${position}",
            };
            var proto = document.location.protocol, host = "getwidget.io", url = proto + "//static." + host;
            var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = url + '/widget-send-button/js/init.js';
            s.onload = function () { WhWidgetSendButton.init(host, proto, options); };
            var x = document.getElementsByTagName('head')[0]; x.appendChild(s);
          })();
        </script>
        <!-- /WhatsApp Widget generated by Widgetify -->
      `;
      break;
    case 'facebook':
      widgetCode = `
        <!-- Facebook Messenger Widget generated by Widgetify -->
        <div id="fb-root"></div>
        <script>
          window.fbAsyncInit = function() {
            FB.init({
              xfbml            : true,
              version          : 'v18.0'
            });
          };

          (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.js';
            fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));
        </script>
        <div class="fb-customerchat"
          attribution="setup_tool"
          page_id="${handle}">
        </div>
        <!-- /Facebook Messenger Widget generated by Widgetify -->
      `;
      break;
    case 'instagram':
      widgetCode = `
        <!-- Instagram Widget generated by Widgetify -->
        <a href="https://instagram.com/${handle}" target="_blank">
          <img src="https://img.shields.io/badge/Instagram-%23E4405F.svg?style=for-the-badge&logo=Instagram&logoColor=white" alt="Instagram Follow" />
        </a>
        <!-- /Instagram Widget generated by Widgetify -->
      `;
      break;
    case 'twitter':
      widgetCode = `
        <!-- Twitter Follow Button generated by Widgetify -->
        <a href="https://twitter.com/${handle}" class="twitter-follow-button" data-show-count="false">Follow @${handle}</a>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        <!-- /Twitter Follow Button generated by Widgetify -->
      `;
      break;
    case 'telegram':
      widgetCode = `
        <!-- Telegram Widget generated by Widgetify -->
        <a href="https://t.me/${handle}">
          <img src="https://img.shields.io/badge/Telegram-2CA5E0?style=for-the-badge&logo=telegram&logoColor=white" alt="Telegram" />
        </a>
        <!-- /Telegram Widget generated by Widgetify -->
      `;
      break;
    case 'linkedin':
      widgetCode = `
        <!-- LinkedIn Follow Button generated by Widgetify -->
        <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
        <div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="en_US" data-type="horizontal" data-theme="dark" data-vanity="${handle}"><a class="LI-simple-link" href='https://www.linkedin.com/in/${handle}?trk=profile-badge'>${handle}</a></div>
        <!-- /LinkedIn Follow Button generated by Widgetify -->
      `;
      break;
    case 'social-share':
      const { shareText, shareUrl, networks } = config;
      widgetCode = `
        <!-- Social Share Widget generated by Widgetify -->
        <div class="social-share">
          <a href="https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}" target="_blank">Facebook</a>
          <a href="https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}" target="_blank">Twitter</a>
          <a href="https://www.linkedin.com/shareArticle?url=${encodeURIComponent(shareUrl)}&title=${encodeURIComponent(shareText)}" target="_blank">LinkedIn</a>
        </div>
        <style>
          .social-share a {
            display: inline-block;
            margin-right: 10px;
            color: #fff;
            padding: 8px 12px;
            border-radius: 5px;
            text-decoration: none;
          }
          .social-share a:nth-child(1) { background-color: #1877F2; }
          .social-share a:nth-child(2) { background-color: #1DA1F2; }
          .social-share a:nth-child(3) { background-color: #0077B5; }
        </style>
        <!-- /Social Share Widget generated by Widgetify -->
      `;
      break;
    case 'google-translate':
      widgetCode = `
        <!-- Google Translate Widget generated by Widgetify -->
        <div id="google_translate_element"></div>
        <script type="text/javascript">
          function googleTranslateElementInit() {
            new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
          }
        </script>
        <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
        <!-- /Google Translate Widget generated by Widgetify -->
      `;
      break;
    case 'youtube':
      widgetCode = `
        <!-- YouTube Widget generated by Widgetify -->
        <a href="https://www.youtube.com/channel/${handle}" target="_blank">
          <img src="https://img.shields.io/badge/YouTube-%23FF0000.svg?style=for-the-badge&logo=YouTube&logoColor=white" alt="YouTube" />
        </a>
        <!-- /YouTube Widget generated by Widgetify -->
      `;
      break;
    case 'github':
      widgetCode = `
        <!-- GitHub Widget generated by Widgetify -->
        <a href="https://github.com/${handle}" target="_blank">
          <img src="https://img.shields.io/badge/GitHub-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub" />
        </a>
        <!-- /GitHub Widget generated by Widgetify -->
      `;
      break;
    case 'twitch':
      widgetCode = `
        <!-- Twitch Widget generated by Widgetify -->
        <a href="https://www.twitch.tv/${handle}" target="_blank">
          <img src="https://img.shields.io/badge/Twitch-%239146FF.svg?style=for-the-badge&logo=Twitch&logoColor=white" alt="Twitch" />
        </a>
        <!-- /Twitch Widget generated by Widgetify -->
      `;
      break;
    case 'slack':
      widgetCode = `
        <!-- Slack Widget generated by Widgetify -->
        <a href="${handle}" target="_blank">
          <img src="https://img.shields.io/badge/Slack-%23E01E5A.svg?style=for-the-badge&logo=Slack&logoColor=white" alt="Slack" />
        </a>
        <!-- /Slack Widget generated by Widgetify -->
      `;
      break;
    case 'discord':
      widgetCode = `
        <!-- Discord Widget generated by Widgetify -->
        <a href="https://discord.gg/${handle}" target="_blank">
          <img src="https://img.shields.io/badge/Discord-%235865F2.svg?style=for-the-badge&logo=discord&logoColor=white" alt="Discord" />
        </a>
        <!-- /Discord Widget generated by Widgetify -->
      `;
      break;
      case 'call-now':
        widgetCode = `
          <!-- Call Now Widget generated by Widgetify -->
          <a href="tel:${config.phoneNumber}">
            Call Now
          </a>
          <!-- /Call Now Widget generated by Widgetify -->
        `;
        break;
      case 'review-now':
        widgetCode = `
          <!-- Review Now Widget generated by Widgetify -->
          <a href="${config.reviewUrl}" target="_blank">
            Review Us
          </a>
          <!-- /Review Now Widget generated by Widgetify -->
        `;
        break;
      case 'follow-us':
        const platform = config.followPlatform || 'linkedin';
        let followUrl = '';
        switch (platform) {
          case 'linkedin':
            followUrl = `https://www.linkedin.com/in/${handle}`;
            break;
          case 'instagram':
            followUrl = `https://www.instagram.com/${handle}`;
            break;
          case 'youtube':
            followUrl = `https://www.youtube.com/channel/${handle}`;
            break;
        }
        widgetCode = `
          <!-- Follow Us on ${platform} Widget generated by Widgetify -->
          <a href="${followUrl}" target="_blank">
            Follow us on ${platform}
          </a>
          <!-- /Follow Us on ${platform} Widget generated by Widgetify -->
        `;
        break;
    default:
      widgetCode = '<!-- Unknown Widget Type -->';
  }

  return widgetCode;
};

export type WidgetType = 'whatsapp' | 'facebook' | 'instagram' | 'twitter' | 'telegram' | 'linkedin' | 'social-share' | 'google-translate' | 'youtube' | 'github' | 'twitch' | 'slack' | 'discord' | 'call-now' | 'review-now' | 'follow-us';

export type BubbleStyle = 'modern' | 'rounded' | 'minimal' | 'bubble' | 'flat' | 'custom';

export interface WidgetConfig {
  type: WidgetType;
  handle?: string;
  welcomeMessage?: string;
  position: 'left' | 'right';
  primaryColor: string;
  size: 'small' | 'medium' | 'large';
  networks?: string[];
  shareText?: string;
  shareUrl?: string;
  phoneNumber?: string;
  reviewUrl?: string;
  followPlatform?: 'linkedin' | 'instagram' | 'youtube';
  // New chat bubble styling properties
  bubbleStyle?: BubbleStyle;
  bubbleBorderRadius?: string;
  bubbleBackgroundColor?: string;
  bubbleTextColor?: string;
}
